###
GET http://localhost:3000/api/bookrepo

###
GET http://localhost:3000/api/bookrepo/2

###
POST http://localhost:3000/api/bookRepo
Content-Type: application/json

{
    "title": "Python",
    "author": "Alex",
    "genre":"CLassic",
    "published_year": 2015,
    "isbn":876545672200,
    "price":40.2,
    "stock_quantity":15
    
    
}

###
PUT http://localhost:3000/api/bookRepo/4
Content-Type: application/json

{

    "title": "Web development",
    "author": "peter",
    "genre":"extravangaza",
    "published_year": 2010,
    "isbn":56782200000000,
    "price":20.2,
    "stock_quantity":30
}

###
DELETE http://localhost:3000/api/bookRepo/15